doc: added section for `customUserProperties.update`
HiveHQ/HiveSdkDocs pull request #27
Opened 2022-10-24 20:56 UTC by ledo01

2022-10-24 20:57 UTC, ledo01 commented
Copy is not one of my talent, so lmk if you have a better one!

2022-10-24 20:58 UTC, ledo01 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[0.5d] new SDK command: "add custom user prop"](https://trello.com/c/3fq6i01G/12742-05d-new-sdk-command-add-custom-user-prop)

2022-10-27 19:36 UTC, prateekmadhikar requested changes
Few things to address! And:

- Lets add a blurb like we have in other sections to let users know that this wont work until the user is authenticated. We can use this copy:

```
<aside class='notice'>
  Users will not be have their custom user properties set or updated until they're "authenticated" via the SDK. In practice, this means that a <code>customUserProperties.update</code> command will be processed immediately for users who have been "autenticated" by a previous <code>emailSignup</code> or <code>phoneNumberSignup</code> command. For users who weren't "authenticated" before a <code>customUserProperties.update</code> command is made, the <code>customUserProperties.update</code> command will be "buffered" by the SDK and processed immediately following a future <code>emailSignup</code> or <code>phoneNumberSignup</code> command (which can potentially happen in the future on a separate pageview or session entirely).
</aside>
```

- Can you double check that the formatting looks fine? I ran the `docker compose` and this branch (and master too) looks weird locally but it looks fine on prod? Pls confirm all is fine on prod (sdk.hive.co) after you ship and deploy!

![image](https://user-images.githubusercontent.com/4978606/198382400-dd2abcad-1577-4283-a7bb-57fc346f072f.png)

2022-10-27 19:36 UTC, prateekmadhikar commented on source/index.html.md
> +# Add Custom User Properties
```suggestion
# Set Custom User Properties
```

2022-10-27 19:36 UTC, prateekmadhikar commented on source/index.html.md
> +This command will add and update custom user properties for the current user.
```suggestion
This command will set custom user properties on the currently "authenticated" user. Any custom user properties that did not exist before will get created and any existing custom user properties that do exist will be updated.
```

2022-10-27 19:36 UTC, prateekmadhikar commented on source/index.html.md
> +```javascript
i believe we need to add this to add a header for the code block!

![image](https://user-images.githubusercontent.com/4978606/198380988-adb50dfd-5222-4f66-b64d-531c5f13a87b.png)

```suggestion
> Use the following command to set custom user properties on the authenticated user.

```javascript
```

2022-10-27 19:36 UTC, prateekmadhikar commented on source/index.html.md
> +This command will add and update custom user properties for the current user.
lets also move this below the code block - i think thats necessary to do!

2022-10-27 19:36 UTC, prateekmadhikar commented on source/index.html.md
> +The third argument is an object of the custom properties name as keys with their values as the object values. This call will created any non-existing properties and update the value of any existing o
I think someone who reads this documentation can understand it fairly quickly and easily without this blurb! Maybe, instead, we can let the reader know that the value's must be strings and if not they will get converted to strings when saved onto the user (its a db design thing.. lowkey sucks lol)

```suggestion
Note that the values for each custom user property must be a string. Any value passed in that is not a string will be saved as a string.
```

2022-10-28 15:12 UTC, ledo01 commented
> Can you double check that the formatting looks fine? I ran the docker compose and this branch (and master too) looks weird locally but it looks fine on prod? Pls confirm all is fine on prod (sdk.hive.co) after you ship and deploy!

I think it's because we are running an older version of slate than the one used in the container. Looks like we are on v2.0.0 and, unfortunately, this version isn't available on docker hub and not worth the trouble of making one. 

I'll make sure to check on prod thought!

2022-10-28 16:06 UTC, prateekmadhikar approved these changes
lgtome!

2022-10-28 17:09 UTC, merged